# This is a basic workflow to help you get started with Actions
name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the eleven branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
            sudo dpkg --add-architecture i386 && sudo apt-get update -qq
            sudo apt-get install --no-install-recommends -y g++ libncurses5-dev libelf1:i386 lib32stdc++6 autoconf libtool bison flex autopoint xsltproc docbook-xsl intltool pkg-config gperf
            BUILD_DIR="${PWD}/release/src-rt-9.x/src"
            export PATH="$PATH:${BUILD_DIR}/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin"
            make -C $BUILD_DIR RT-AC1200G+ 2>&1 | tee ${BUILD_DIR}/compile.log

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          mkdir Final
          BUILD_DIR="${PWD}/release/src-rt-9.x/src"
          mv ${BUILD_DIR}/image/RT-AC1200G+_*.trx Final/
          mv ${BUILD_DIR}/image/RT-AC1200G+_*.md5 Final/
          mv ${BUILD_DIR}/compile.log Final/
          BUILD_DATE="$(date +%Y%m%d%H%M)"
          echo "ReleaseName=PHICOMM_K2P_${BUILD_DATE}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        name: Upload
        with:
          name: ${{ steps.prepareArtifact.outputs.ReleaseName }}
          path: "Final/*"
